WITH products AS (
    SELECT * FROM {{ ref('stg_products') }}
),

product_sales AS (
    SELECT
        PRODUCT_ID,
        SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
        SUM(NET_PRICE) AS TOTAL_REVENUE,
        AVG(DISCOUNT) AS AVG_DISCOUNT,
        COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
    FROM {{ ref('fct_sales') }}
    GROUP BY PRODUCT_ID
)

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.BRAND_NAME,
    p.CATEGORY_NAME,
    p.MODEL_YEAR,
    p.LIST_PRICE,
    COALESCE(ps.TOTAL_UNITS_SOLD, 0) AS TOTAL_UNITS_SOLD,
    COALESCE(ps.TOTAL_REVENUE, 0) AS TOTAL_REVENUE,
    COALESCE(ps.AVG_DISCOUNT, 0) AS AVG_DISCOUNT,
    COALESCE(ps.TOTAL_ORDERS, 0) AS TOTAL_ORDERS
FROM products p
LEFT JOIN product_sales ps ON p.PRODUCT_ID = ps.PRODUCT_ID