SELECT
    STAFF_NAME,
    STORE_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(NET_PRICE) AS TOTAL_REVENUE,
    SUM(NET_PRICE) / NULLIF(COUNT(DISTINCT ORDER_ID), 0) AS AVG_ORDER_VALUE,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM {{ ref('fct_sales') }}
GROUP BY STAFF_NAME, STORE_NAME
ORDER BY TOTAL_REVENUE DESC