SELECT
    PRODUCT_NAME,
    BRAND_NAME,
    CATEGORY_NAME,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(NET_PRICE) AS TOTAL_REVENUE,
    AVG(DISCOUNT) AS AVG_DISCOUNT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    RANK() OVER (ORDER BY SUM(NET_PRICE) DESC) AS REVENUE_RANK,
    RANK() OVER (ORDER BY SUM(QUANTITY) DESC) AS UNITS_SOLD_RANK
FROM {{ ref('fct_sales') }}
GROUP BY PRODUCT_NAME, BRAND_NAME, CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC