SELECT
    DATE_TRUNC('month', ORDER_DATE) AS MONTH,
    STORE_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    SUM(NET_PRICE) AS TOTAL_REVENUE,
    SUM(NET_PRICE) / NULLIF(COUNT(DISTINCT ORDER_ID), 0) AS AVG_ORDER_VALUE,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM {{ ref('fct_sales') }}
GROUP BY DATE_TRUNC('month', ORDER_DATE), STORE_NAME
ORDER BY MONTH DESC, TOTAL_REVENUE DESC